[package]
name = "Rust-Webcrawler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soup = "0.5.0"
url = "2.1.1"
reqwest = "0.8.3"
regex = "1"